### ISSUE TITLE
update the Tesseract to latest version?

### ISSUE THREAD

**Issue by EzimetYusup** [scott0123/Tesseract-macOS#6]
@scott0123  are you planning the core Tesseract to latest version? if not can you point me to how?

**Comment by scott0123** [comment]
The latest version of Tesseract is 4.0.0 which uses a trained LSTM model to do OCR. Since I do not actively follow their development updates any more, I'm not sure if they guarantee backwards compatibility for their bundled library API usage at the time of writing this. You will have to test this.

Nonetheless, If you would like to do this yourself and submit a pull request later, you are welcome to do so.

Here is an outline of what to do, it's quite simple:

1. Clone the latest stable release of Tesseract (Look [HERE](https://github.com/tesseract-ocr/tesseract/branches))
2. Build the Tesseract engine from source on a macOS device by following the instructions [HERE](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos-with-homebrew) (I recommend homebrew)
3. Find where you compiled the static library file `libtesseract.a`, it's usually under `/usr/local/Cellar/` but this depends on how you configured your homebrew settings. Make sure this is version 4.0.
4. Replace the `Screenshot-OCR/lib/libtesseract.a` file with your new compiled `libtesseract.a`.
5. Open up this project in Xcode and verify functionality, be thorough.
6. Assuming the above works, open a new branch and commit your changes there.
6. Make a pull request from your branch to my master branch, so that I can review and merge your updates.

**Comment by gioele-santi** [comment]
Hello, I am trying to do this update but I found some errors when trying to run the updated project. Maybe you have some suggestions on what I can do...
I have compiled version 4.1.0 of libtesseract and replaced the one in the example. Then I have also replaced trained data with latest eng.traineddata (I am making this because I need to use latest trained data).

When I run the app I get this message: 
**Error opening data file /Users/.../Library/Developer/Xcode/DerivedData/Screenshot-OCR-ftkldbrhsmiqdtdtkkhcqxxjjftc/Build/Products/Debug/Screenshot-OCR.app/Contents/Resources/eng.traineddata**

**Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!**

For what I can see, new trained data was included correctly in the same folder. I even cleaned project and derived data, but nothing to do. Did you experience something similar when creating the project?

**Comment by scott0123** [comment]
No I have not run into this issue.

However, here are some suggestions that would help you debug this issue:
1. Check out all references to the `NSString *absoluteDataPath` variable (declared on line 27 in SLTesseract.mm) and see if you made any unintended changes to this variable.
2. Make sure the `NSString *absoluteDataPath` variable is set to `[[NSBundle mainBundle].bundlePath stringByAppendingString:@"/Contents/Resources/"];` within the initializer (line 37 in SLTesseract.mm). The environment variable should also be set (line 39). 
3. Make sure your `tessdata` folder is copied to the final build. You can check this by going to `TARGETS > Screenshot-OCR > Build Phases > Copy Bundle Resources` and making sure that this folder is there.

I have attached the following screenshot for your convenience in part 3.
![image](https://user-images.githubusercontent.com/29332207/65536085-ae478f80-ded0-11e9-81a6-56ad71477283.png)

Best of luck,
Scott

**Comment by scott0123** [comment]
Additionally, if you fix this issue and can verify for me that it works better than the old Tesseract version, I would not mind merging this update as a pull request.

**Comment by gioele-santi** [comment]
Hi, I don't know why. I didn't change anything from your files but it didn't work.
Anyway I found a solution. It was looking for the data in the **Resources** folder instead of **tessdata** subfolder. I changed line 37 in SLTesseract.mm from this:

`[[NSBundle mainBundle].bundlePath stringByAppendingString:@"/Contents/Resources/"];`

to this:

`[[NSBundle mainBundle].bundlePath stringByAppendingString:@"/Contents/Resources/tessdata"];`

and it worked.

I will make a pull request after some other tests.

Maybe I will try again with a fresh clone of repository with new library and data added before compiling the first time.

**Comment by scott0123** [comment]
@EzimetYusup Resolved in #7 
Closing this issue now.

**Comment by dimitristsilis** [comment]
Now that Tesseract 5.x is available, perhaps it's time to update Tesseract-MacOS as well! The same steps still apply? I would like to help, but I don't know how.

**Comment by scott0123** [comment]
Hi @dimitristsilis, could you open a new issue titled "Update tesseract library to 5.x". Once you do, I can take a look at this once I have some spare time. In the meantime you can try to take a stab at it if you like. The step-by-step guide is outlined in my first comment on this issue. That being said, it is from 2019 so I cannot say for sure whether it still holds true step for step.

**Comment by dimitristsilis** [comment]
Done.

**Comment by EzimetYusup** [comment]
@scott0123  thanks.
